#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

PROJECT_NAME := LZRTag_Main

EXTRA_COMPONENT_DIRS := $(XASCODE_PATH)/ESP32/

include $(IDF_PATH)/make/project.mk
